FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# 
RUN npm install

# Copy all source code into the docker image
COPY . .

# expose a port please
EXPOSE 8080

# do the things
CMD ["node", "server.js"]